name: "CheckMate - PR Review Checklist Bot"
description: "A GitHub Action to automate PR review checklists. CheckMate posts a predefined checklist for tagged reviewers to ensure thorough PR reviews."

inputs:
  github_token:
    description: "The GitHub token for authentication and API access."
    required: true
  message_header:
    description: "The header of the message that will be posted with the checklist."
    default: "### :robot: CheckMate - PR Review Checklist"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "check-circle" # A checkmark icon to represent the action
  color: "blue"
