import os
import requests

# GitHub API details
GITHUB_API_URL = "https://api.github.com"
REPO = os.getenv("GITHUB_REPOSITORY")  # e.g., "owner/repo"
PR_NUMBER = os.getenv("GITHUB_REF").split("/")[-2]  # Extract PR number from ref
GITHUB_TOKEN = os.getenv("INPUT_GITHUB_TOKEN")

# Checklist template
CHECKLIST = """
### **PR Review Checklist**

- [ ] Code compiles and passes all tests.
- [ ] Solution produces the expected results.
- [ ] Code is clean, readable, and adheres to standards.
- [ ] Documentation is updated.
- [ ] Commit messages and changelogs are clear.
- [ ] Examples and tests are updated.
- [ ] Versioning is evaluated and justified.
- [ ] Review feedback is addressed.
- [ ] Integration and deployment readiness is confirmed.

---

*This checklist was automatically generated by the PR Checklist Bot.*
"""

def get_pr_details():
    """Fetch PR details to get the list of reviewers."""
    url = f"{GITHUB_API_URL}/repos/{REPO}/pulls/{PR_NUMBER}"
    headers = {
        "Authorization": f"Bearer {GITHUB_TOKEN}",
        "Accept": "application/vnd.github.v3+json",
    }
    response = requests.get(url, headers=headers)
    if response.status_code == 200:
        return response.json()
    else:
        print(f"Failed to fetch PR details: {response.status_code}")
        return None

def post_comment(reviewer):
    """Post the checklist comment and tag the reviewer."""
    url = f"{GITHUB_API_URL}/repos/{REPO}/issues/{PR_NUMBER}/comments"
    headers = {
        "Authorization": f"Bearer {GITHUB_TOKEN}",
        "Accept": "application/vnd.github.v3+json",
    }
    body = f"@{reviewer}, please review this PR. Here's a checklist to guide you:\n\n{CHECKLIST}"
    data = {"body": body}
    response = requests.post(url, headers=headers, json=data)
    if response.status_code == 201:
        print(f"Checklist posted for reviewer: {reviewer}")
    else:
        print(f"Failed to post comment: {response.status_code}")

def main():
    pr_details = get_pr_details()
    if pr_details:
        reviewers = pr_details.get("requested_reviewers", [])
        for reviewer in reviewers:
            post_comment(reviewer["login"])

if __name__ == "__main__":
    main()
